### ISSUE TITLE
示例不严谨

### ISSUE THREAD

**Issue by miss85246** [iswbm/magic-python#24]
第二节，end的使用方法，你的示例中不管那种都必被if或者else捕获，然后直接return，压根就走不到end的地方，我没有亲自实验，但是没报错不能说明这个东西有用，只能证明这个东西没有报错，请考虑一个严谨的例子。不然怕是误人误己

**Comment by miss85246** [comment]
还有字典是可以排序的，老哥，你用了一个字典生成式，这能证明字典可以排序？？？头一次听说，你只是证明了他可迭代，无法证明它可排序！！！

**Comment by iswbm** [comment]
> 第二节，end的使用方法，你的示例中不管那种都必被if或者else捕获，然后直接return，压根就走不到end的地方，我没有亲自实验，但是没报错不能说明这个东西有用，只能证明这个东西没有报错，请考虑一个严谨的例子。不然怕是误人误己

原文说，"在 Python 这种严格缩进的语言里并没有必要这样做"，并没有说 end 这个东西有用。

另，如果语法不过关，解释器会直接报语法错误，没有报错，自然说明语法支持。文中举例从来没有说 end 有用。

**Comment by iswbm** [comment]
> 还有字典是可以排序的，老哥，你用了一个字典生成式，这能证明字典可以排序？？？头一次听说，你只是证明了他可迭代，无法证明它可排序！！！

不知所云。。

请参考官方说明：[What’s New In Python 3.6](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-compactdict)

**Comment by iswbm** [comment]
> 还有字典是可以排序的，老哥，你用了一个字典生成式，这能证明字典可以排序？？？头一次听说，你只是证明了他可迭代，无法证明它可排序！！！

python2.7 到 python3.6 同样代码，输出结果差异那么明显，你却只关注到使用 字典生成式？？
