### ISSUE TITLE
and 和 or 的短路效应 存在歧义

### ISSUE THREAD

**Issue by CNDrwei** [iswbm/magic-python#5]
http://magic.iswbm.com/zh/latest/c01/c01_07.html
当一个 or 表达式中所有值都为真，Python会选择第一个值

当一个 and 表达式 所有值都为真，Python 会选择第二个值。是最后一个真, 不要用第二个这样的词, 容易让人误导

**Comment by iswbm** [comment]
谢谢指出，已更正
